### ISSUE TITLE
Proxy doesn't work for path: /

### ISSUE THREAD

**Issue by jtolsma** [YakLabs/kube-openresty-ingress#4]
If path: / is set for the ingress the proxy does not work.

Works:
- host: foo.bar.com
  http:
    paths:
  - path: /foo
    backend:
      serviceName: echoheaders-x
      servicePort: 80

Does not work:
- host: foo.bar.com
  http:
    paths:
  - path: /
    backend:
      serviceName: echoheaders-x
      servicePort: 80

**Comment by bakins** [comment]
@jtolsma will you see if #3 fixes the issue?

**Comment by jtolsma** [comment]
Just tested and confirmed that #3 fixes the issue, thanks!
